# port should be 61617 - see server config
jms.url_provider=tcp://<host>:<port> 
# FTP Configuration
ftp.host=<ftp_host>
ftp.login=<ftp_login>
#Specify which FTP authentication method to use
# if 'KEY_MODE' ftp.password is ignored and default key or ftp.keyPath specified key is used
# if 'PASSWD_MODE' ftp.password is used and ftp.keyPath is ignored
ftp.auth.mode=key
ftp.password=<ftp_pass>
# Path to the private key used for SFTP authentication.
# Default is ./conf/epims-id_rsa next to the distribution.
# You can use an absolute path if desired.
ftp.keyPath=./conf/epims-id_rsa
# Transfer mode to use. FTP_MODE or SFTP_MODE. FTP_MODE only support PASSWD_MODE authentication method
ftp.mode=SFTP_MODE
logging.level.org.springframework.boot=WARN




